//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensPedidos
    {
        public int Codigo_produto { get; set; }
        public string DescricaoProduto { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> PesoLiquido { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public Nullable<decimal> PesoTotal { get; set; }
        public Nullable<int> Codigo_pedido { get; set; }
        public int Id_item { get; set; }
    
        public virtual Produtos Produtos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
